name: Deploy Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - uses: actions/setup-node@v2
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install Dependencies
        run: npm install --no-audit --no-fund --no-optional
      - name: Run Eslint
        run: npm run eslint
      - name: Unit Testing
        run: npm test
      - name: Build Proyect
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1